version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
  build: 
    context: ./backend
    dockerfile: Dockerfile.backend.dev
  ports:
    - "8000:8000"
  volumes:
    - ./backend:/app
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - REDIS_URL=redis://redis:6379
  depends_on:
    - redis

redis:
  image: redis:alpine
  ports:
    - "6379:6379"
